let ar=[1,"vini",true,null,false,"hala",7]
console.log(typeof(ar))
console.log(ar.length)
console.log(ar[1])
console.log(ar.indexOf("hala"))
ar.push(10)
// console.log(ar)
// console.log(ar.pop())
// console.log(ar.shift())
// console.log(ar[1]="ney")
console.log(ar[ar.indexOf("hala")="suiii"])